apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
        - name: coworking
          image: 151465357300.dkr.ecr.us-east-1.amazonaws.com/coworking:2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: "/readiness_check"
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: analytic-map-1
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytic-secret
                  key: DB_PASSWORD
      restartPolicy: Always